/*
 * Created on 18 oct. 2014 ( Time 14:09:46 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package org.demo.persistence.services.fake;

import java.util.List;
import java.util.Map;

import org.demo.bean.jpa.ExempleEntity;
import org.demo.persistence.commons.fake.GenericFakeService;
import org.demo.persistence.services.ExemplePersistence;

/**
 * Fake persistence service implementation ( entity "Exemple" )
 *
 * @author Telosys Tools Generator
 */
public class ExemplePersistenceFAKE extends GenericFakeService<ExempleEntity> implements ExemplePersistence {

	public ExemplePersistenceFAKE () {
		super(ExempleEntity.class);
	}
	
	protected ExempleEntity buildEntity(int index) {
		ExempleEntity entity = new ExempleEntity();
		// Init fields with mock values
		entity.setId( nextInteger() ) ;
		entity.setNom( nextString() ) ;
		return entity ;
	}
	
	
	public boolean delete(ExempleEntity entity) {
		log("delete ( ExempleEntity : " + entity + ")" ) ;
		return true;
	}

	public boolean delete( Integer id ) {
		log("delete ( PK )") ;
		return true;
	}

	public void insert(ExempleEntity entity) {
		log("insert ( ExempleEntity : " + entity + ")" ) ;
	}

	public ExempleEntity load( Integer id ) {
		log("load ( PK )") ;
		return buildEntity(1) ; 
	}

	public List<ExempleEntity> loadAll() {
		log("loadAll()") ;
		return buildList(40) ;
	}

	public List<ExempleEntity> loadByNamedQuery(String queryName) {
		log("loadByNamedQuery ( '" + queryName + "' )") ;
		return buildList(20) ;
	}

	public List<ExempleEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) {
		log("loadByNamedQuery ( '" + queryName + "', parameters )") ;
		return buildList(10) ;
	}

	public ExempleEntity save(ExempleEntity entity) {
		log("insert ( ExempleEntity : " + entity + ")" ) ;
		return entity;
	}

	public List<ExempleEntity> search(Map<String, Object> criteria) {
		log("search (criteria)" ) ;
		return buildList(15) ;
	}

	@Override
	public long countAll() {
		return 0 ;
	}

}
