/*
 * Created on 18 oct. 2014 ( Time 14:09:46 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */

package org.demo.persistence.services.jpa;


import javax.persistence.EntityManager;
import javax.persistence.PersistenceException;
import javax.persistence.Query;

import org.demo.bean.jpa.ExempleEntity;
import org.demo.persistence.commons.jpa.GenericJpaService;
import org.demo.persistence.commons.jpa.JpaOperation;
import org.demo.persistence.services.ExemplePersistence;

/**
 * JPA implementation for basic persistence operations ( entity "Exemple" )
 * 
 * @author Telosys Tools Generator
 *
 */
public class ExemplePersistenceJPA extends GenericJpaService<ExempleEntity, Integer> implements ExemplePersistence {

	/**
	 * Constructor
	 */
	public ExemplePersistenceJPA() {
		super(ExempleEntity.class);
	}

	@Override
	public ExempleEntity load( Integer id ) {
		return super.load( id );
	}

	@Override
	public boolean delete( Integer id ) {
		return super.delete( id );
	}

	@Override
	public boolean delete(ExempleEntity entity) {
		if ( entity != null ) {
			return super.delete( entity.getId() );
		}
		return false ;
	}

	@Override
	public long countAll() {
		// JPA operation definition 
		JpaOperation operation = new JpaOperation() {
			@Override
			public Object exectue(EntityManager em) throws PersistenceException {
				Query query = em.createNamedQuery("ExempleEntity.countAll");
				return query.getSingleResult() ;
			}
		} ;
		// JPA operation execution 
		return (Long) execute(operation);
	}

}
