/*
 * Created on 20 oct. 2014 ( Time 09:24:20 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.eventManager.bean.jpa;

import java.io.Serializable;
import java.sql.Timestamp;
import java.util.ArrayList;
//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Persistence;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.TypedQuery;
import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.ParameterExpression;
import javax.persistence.criteria.Root;

import com.eventManager.persistence.PersistenceServiceProvider;
import com.eventManager.persistence.services.EventsPersistence;
import com.eventManager.persistence.services.UsersPersistence;

/**
 * Persistent class for entity stored in table "EVENTS"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="EVENTS", schema="APP" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="EventsEntity.countAll", query="SELECT COUNT(x) FROM EventsEntity x" )
} )
public class EventsEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="EVENT_ID", nullable=false)
    private Integer    eventId      ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="URL", nullable=false, length=50)
    private String     url          ;

    @Column(name="NAME", nullable=false, length=50)
    private String     name         ;

    @Column(name="ADDRESS", nullable=false, length=50)
    private String     address      ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DATE_BEGINNING")
    private Date       dateBeginning ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DATE_END")
    private Date       dateEnd      ;

    @Column(name="PUBLISHED")
    private Short      published    ;

	// "creatorId" (column "CREATOR_ID") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @OneToMany(mappedBy="events", targetEntity=InscriptionsEntity.class)
    private List<InscriptionsEntity> listOfInscriptions;

    @ManyToOne
    @JoinColumn(name="CREATOR_ID", referencedColumnName="USER_ID")
    private UsersEntity users       ;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public EventsEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setEventId( Integer eventId ) {
        this.eventId = eventId ;
    }
    public Integer getEventId() {
        return this.eventId;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : URL ( VARCHAR ) 
    public void setUrl( String url ) {
        this.url = url;
    }
    public String getUrl() {
        return this.url;
    }

    //--- DATABASE MAPPING : NAME ( VARCHAR ) 
    public void setName( String name ) {
        this.name = name;
    }
    public String getName() {
        return this.name;
    }

    //--- DATABASE MAPPING : ADDRESS ( VARCHAR ) 
    public void setAddress( String address ) {
        this.address = address;
    }
    public String getAddress() {
        return this.address;
    }

    //--- DATABASE MAPPING : DATE_BEGINNING ( TIMESTAMP ) 
    public void setDateBeginning( Date dateBeginning ) {
        this.dateBeginning = dateBeginning;
    }
    public Date getDateBeginning() {
        return this.dateBeginning;
    }

    //--- DATABASE MAPPING : DATE_END ( TIMESTAMP ) 
    public void setDateEnd( Date dateEnd ) {
        this.dateEnd = dateEnd;
    }
    public Date getDateEnd() {
        return this.dateEnd;
    }

    //--- DATABASE MAPPING : PUBLISHED ( SMALLINT ) 
    public void setPublished( Short published ) {
        this.published = published;
    }
    public Short getPublished() {
        return this.published;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setListOfInscriptions( List<InscriptionsEntity> listOfInscriptions ) {
        this.listOfInscriptions = listOfInscriptions;
    }
    public List<InscriptionsEntity> getListOfInscriptions() {
        return this.listOfInscriptions;
    }

    public void setUsers( UsersEntity users ) {
        this.users = users;
    }
    public UsersEntity getUsers() {
        return this.users;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(eventId);
        sb.append("]:"); 
        sb.append(url);
        sb.append("|");
        sb.append(name);
        sb.append("|");
        sb.append(address);
        sb.append("|");
        sb.append(dateBeginning);
        sb.append("|");
        sb.append(dateEnd);
        sb.append("|");
        sb.append(published);
        return sb.toString(); 
    } 
    
    public void add(String userId, String nameEvent, String adressEvent, Timestamp debut, Timestamp fin, short published) {
    	EventsPersistence service = PersistenceServiceProvider.getService(EventsPersistence.class);
    	UsersPersistence service2 = PersistenceServiceProvider.getService(UsersPersistence.class);
    	EventsEntity event = new EventsEntity();
    	event.setName(nameEvent);
    	event.setAddress(adressEvent);
    	event.setPublished(published);
    	event.setDateBeginning(debut);
    	event.setDateEnd(fin);
    	event.setUrl("#"+nameEvent);
    	event.setUsers(service2.load(Integer.parseInt(userId)));
    	service.insert(event);
    	
	}
    
    public List<EventsEntity> getAllEventsCreated(String userId) {
    	EntityManagerFactory emf = Persistence.createEntityManagerFactory("persistence-unit1");
    	//UsersPersistence service2 = PersistenceServiceProvider.getService(UsersPersistence.class);
		EntityManager em = emf.createEntityManager();
		UsersEntity user = em.find(UsersEntity.class, Integer.parseInt(userId));
		EventsEntity event = new EventsEntity();
		
		TypedQuery<EventsEntity> query = em.createQuery("SELECT event FROM EventsEntity as event WHERE event.users.mail='"+user.getMail()+"'", EventsEntity.class);
		List<EventsEntity> resultList = query.getResultList();
    	
		return resultList;
	}
    
    public List<EventsEntity> getAllEventsParticipated(String userID) {
    	EntityManagerFactory emf = Persistence.createEntityManagerFactory("persistence-unit1");
    	//UsersPersistence service2 = PersistenceServiceProvider.getService(UsersPersistence.class);
		EntityManager em = emf.createEntityManager();
		UsersEntity user = em.find(UsersEntity.class, Integer.parseInt(userID));
		EventsEntity event = new EventsEntity();
		InscriptionsEntity inscription = new InscriptionsEntity();
		TypedQuery<InscriptionsEntity> query = em.createQuery("SELECT inscription FROM InscriptionsEntity as inscription WHERE inscription.mail='"+user.getMail()+"'", InscriptionsEntity.class);
		System.out.println("executed");
		List<InscriptionsEntity> result = query.getResultList();
		List<EventsEntity> resultList = new ArrayList<EventsEntity>();
		for (InscriptionsEntity e : result){
			resultList.add(e.getEvents());
		}
    	return resultList;
    	
	}
    
    public String delete(int userId, int rowId) {
    	EntityManagerFactory emf = Persistence.createEntityManagerFactory("persistence-unit1");
    	EntityManager em = emf.createEntityManager();
		EventsEntity event = em.find(EventsEntity.class, rowId);
		if(event.getUsers().getUserId()==userId){
			System.out.println(event.getName());
			System.out.println(event.getEventId());
			em.getTransaction().begin();
			em.remove(event);
			em.getTransaction().commit();
			return "success";
		}
		else{
			return "failed";
		}
	}
    
    public String publish(int userId, int rowId) {
    	EntityManagerFactory emf = Persistence.createEntityManagerFactory("persistence-unit1");
    	EntityManager em = emf.createEntityManager();
		EventsEntity event = em.find(EventsEntity.class, rowId);
		if(event.getUsers().getUserId()==userId){
			System.out.println(event.getName());
			System.out.println(event.getEventId());
			em.getTransaction().begin();
			event.setPublished((short)1);
			em.getTransaction().commit();
			return "success";
		}
		else{
			return "failed";
		}
	}

}
