/*
 * Created on 19 oct. 2014 ( Time 15:57:32 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.eventManager.persistence.services.fake;

import java.util.List;
import java.util.Map;

import com.eventManager.bean.jpa.InscriptionsEntity;
import com.eventManager.persistence.commons.fake.GenericFakeService;
import com.eventManager.persistence.services.InscriptionsPersistence;

/**
 * Fake persistence service implementation ( entity "Inscriptions" )
 *
 * @author Telosys Tools Generator
 */
public class InscriptionsPersistenceFAKE extends GenericFakeService<InscriptionsEntity> implements InscriptionsPersistence {

	public InscriptionsPersistenceFAKE () {
		super(InscriptionsEntity.class);
	}
	
	protected InscriptionsEntity buildEntity(int index) {
		InscriptionsEntity entity = new InscriptionsEntity();
		// Init fields with mock values
		entity.setInscriptionId( nextInteger() ) ;
		entity.setMail( nextString() ) ;
		entity.setName( nextString() ) ;
		entity.setSurname( nextString() ) ;
		entity.setCompany( nextString() ) ;
		return entity ;
	}
	
	
	public boolean delete(InscriptionsEntity entity) {
		log("delete ( InscriptionsEntity : " + entity + ")" ) ;
		return true;
	}

	public boolean delete( Integer inscriptionId ) {
		log("delete ( PK )") ;
		return true;
	}

	public void insert(InscriptionsEntity entity) {
		log("insert ( InscriptionsEntity : " + entity + ")" ) ;
	}

	public InscriptionsEntity load( Integer inscriptionId ) {
		log("load ( PK )") ;
		return buildEntity(1) ; 
	}

	public List<InscriptionsEntity> loadAll() {
		log("loadAll()") ;
		return buildList(40) ;
	}

	public List<InscriptionsEntity> loadByNamedQuery(String queryName) {
		log("loadByNamedQuery ( '" + queryName + "' )") ;
		return buildList(20) ;
	}

	public List<InscriptionsEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) {
		log("loadByNamedQuery ( '" + queryName + "', parameters )") ;
		return buildList(10) ;
	}

	public InscriptionsEntity save(InscriptionsEntity entity) {
		log("insert ( InscriptionsEntity : " + entity + ")" ) ;
		return entity;
	}

	public List<InscriptionsEntity> search(Map<String, Object> criteria) {
		log("search (criteria)" ) ;
		return buildList(15) ;
	}

	@Override
	public long countAll() {
		return 0 ;
	}

}
