
/*
 * Created on 18 oct. 2014 ( Time 14:09:46 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package org.demo.mock;

import java.util.LinkedList;
import java.util.List;

import org.demo.bean.jpa.ExempleEntity;
import org.demo.mock.tool.MockValues;

public class ExempleEntityMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public ExempleEntity createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextInteger() );
	}
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public ExempleEntity createInstance( Integer id ) {
		ExempleEntity entity = new ExempleEntity();
		// Init Primary Key fields
		entity.setId( id) ;
		// Init Data fields
		entity.setNom( mockValues.nextString(50) ) ; // java.lang.String 
		// Init Link fields (if any)
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<ExempleEntity> createList(int count) {
		List<ExempleEntity> list = new LinkedList<ExempleEntity>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
