/*
 * Created on 19 oct. 2014 ( Time 15:57:54 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.eventManager.test.persistence;


import com.eventManager.bean.jpa.EventsEntity;
import com.eventManager.persistence.PersistenceServiceProvider;
import com.eventManager.persistence.services.EventsPersistence;

import org.junit.Assert;
import org.junit.Test;

/**
 * JUnit test case for Events persistence service
 * 
 * @author Telosys Tools Generator
 *
 */
public class EventsPersistenceTest 
{
	@Test
	public void test1() {
		
		System.out.println("Test count ..." );
		
		EventsPersistence service = PersistenceServiceProvider.getService(EventsPersistence.class);
		System.out.println("CountAll = " + service.countAll() );
	}	
}
