/*
 * Created on 19 oct. 2014 ( Time 15:57:32 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.eventManager.test.persistence;


import com.eventManager.bean.jpa.InscriptionsEntity;
import com.eventManager.mock.InscriptionsEntityMock;
import com.eventManager.persistence.PersistenceServiceProvider;
import com.eventManager.persistence.services.InscriptionsPersistence;

import org.junit.Assert;
import org.junit.Test;

/**
 * JUnit test case for Inscriptions persistence service
 * 
 * @author Telosys Tools Generator
 *
 */
public class InscriptionsPersistenceTest 
{
	@Test
	public void test1() {
		
		System.out.println("Test count ..." );
		
		InscriptionsPersistence service = PersistenceServiceProvider.getService(InscriptionsPersistence.class);
		System.out.println("CountAll = " + service.countAll() );
	}
	
	@Test
	public void test2() {
		
		System.out.println("Test Inscriptions persistence : delete + load ..." );
		
		InscriptionsPersistence service = PersistenceServiceProvider.getService(InscriptionsPersistence.class);
		
		InscriptionsEntityMock mock = new InscriptionsEntityMock();
		
		// TODO : set primary key values here 
		process( service, mock, 0  );
		// process( service, mock, ... );
	}

	private void process(InscriptionsPersistence service, InscriptionsEntityMock mock, Integer inscriptionId ) {
		System.out.println("----- "  );
		System.out.println(" . load : " );
		InscriptionsEntity entity = service.load( inscriptionId );
		if ( entity != null ) {
			// Found 
			System.out.println("   FOUND : " + entity );
			
			// Save (update) with the same values to avoid database integrity errors  
			System.out.println(" . save : " + entity );
			service.save(entity);
			System.out.println("   saved : " + entity );
		}
		else {
			// Not found 
			System.out.println("   NOT FOUND" );
			// Create a new instance 
			entity = mock.createInstance( inscriptionId ) ;
			Assert.assertNotNull(entity);

			// This entity references the following entities : 
			// . Events
			/* Insert only if references are OK
			// Try to insert the new instance
			System.out.println(" . insert : " + entity );
			service.insert(entity);
			System.out.println("   inserted : " + entity );
			*/

			System.out.println(" . delete : " );
			boolean deleted = service.delete( inscriptionId );
			System.out.println("   deleted = " + deleted);
		}		
	}
}
