/*
 * Created on 19 oct. 2014 ( Time 15:57:32 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */

package com.eventManager.persistence.services.jpa;


import javax.persistence.EntityManager;
import javax.persistence.PersistenceException;
import javax.persistence.Query;

import com.eventManager.bean.jpa.UsersEntity;
import com.eventManager.persistence.commons.jpa.GenericJpaService;
import com.eventManager.persistence.commons.jpa.JpaOperation;
import com.eventManager.persistence.services.UsersPersistence;

/**
 * JPA implementation for basic persistence operations ( entity "Users" )
 * 
 * @author Telosys Tools Generator
 *
 */
public class UsersPersistenceJPA extends GenericJpaService<UsersEntity, Integer> implements UsersPersistence {

	/**
	 * Constructor
	 */
	public UsersPersistenceJPA() {
		super(UsersEntity.class);
	}

	@Override
	public UsersEntity load( Integer userId ) {
		return super.load( userId );
	}

	@Override
	public boolean delete( Integer userId ) {
		return super.delete( userId );
	}

	@Override
	public boolean delete(UsersEntity entity) {
		if ( entity != null ) {
			return super.delete( entity.getUserId() );
		}
		return false ;
	}

	@Override
	public long countAll() {
		// JPA operation definition 
		JpaOperation operation = new JpaOperation() {
			@Override
			public Object exectue(EntityManager em) throws PersistenceException {
				Query query = em.createNamedQuery("UsersEntity.countAll");
				return query.getSingleResult() ;
			}
		} ;
		// JPA operation execution 
		return (Long) execute(operation);
	}

}
