
/*
 * Created on 19 oct. 2014 ( Time 15:57:32 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.eventManager.mock;

import java.util.LinkedList;
import java.util.List;

import com.eventManager.bean.jpa.UsersEntity;
import com.eventManager.mock.tool.MockValues;

public class UsersEntityMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public UsersEntity createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextInteger() );
	}
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public UsersEntity createInstance( Integer userId ) {
		UsersEntity entity = new UsersEntity();
		// Init Primary Key fields
		entity.setUserId( userId) ;
		// Init Data fields
		entity.setMail( mockValues.nextString(50) ) ; // java.lang.String 
		entity.setName( mockValues.nextString(50) ) ; // java.lang.String 
		entity.setSurname( mockValues.nextString(50) ) ; // java.lang.String 
		entity.setPassword( mockValues.nextString(50) ) ; // java.lang.String 
		entity.setCompany( mockValues.nextString(50) ) ; // java.lang.String 
		// Init Link fields (if any)
		// setListOfEvents( TODO ) ; // List<Events> 
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<UsersEntity> createList(int count) {
		List<UsersEntity> list = new LinkedList<UsersEntity>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
