/*
 * Created on 19 oct. 2014 ( Time 15:57:32 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.eventManager.persistence.services;

import java.util.List;
import java.util.Map;

import com.eventManager.bean.jpa.InscriptionsEntity;

/**
 * Basic persistence operations for entity "Inscriptions"
 * 
 * This Bean has a basic Primary Key : Integer
 *
 * @author Telosys Tools Generator
 *
 */
public interface InscriptionsPersistence {

	/**
	 * Deletes the given entity <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param inscriptions
	 * @return true if found and deleted, false if not found
	 */
	public boolean delete(InscriptionsEntity inscriptions) ;

	/**
	 * Deletes the entity by its Primary Key <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param inscriptionId
	 * @return true if found and deleted, false if not found
	 */
	public boolean delete(Integer inscriptionId) ;

	/**
	 * Inserts the given entity and commit <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param inscriptions
	 */
	public void insert(InscriptionsEntity inscriptions) ;

	/**
	 * Loads the entity for the given Primary Key <br>
	 * @param inscriptionId
	 * @return the entity loaded (or null if not found)
	 */
	public InscriptionsEntity load(Integer inscriptionId) ;

	/**
	 * Loads ALL the entities (use with caution)
	 * @return
	 */
	public List<InscriptionsEntity> loadAll() ;

	/**
	 * Loads a list of entities using the given "named query" without parameter 
	 * @param queryName
	 * @return
	 */
	public List<InscriptionsEntity> loadByNamedQuery(String queryName) ;

	/**
	 * Loads a list of entities using the given "named query" with parameters 
	 * @param queryName
	 * @param queryParameters
	 * @return
	 */
	public List<InscriptionsEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) ;

	/**
	 * Saves (create or update) the given entity <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param inscriptions
	 * @return
	 */
	public InscriptionsEntity save(InscriptionsEntity inscriptions) ;

	/**
	 * Search the entities matching the given search criteria
	 * @param criteria
	 * @return
	 */
	public List<InscriptionsEntity> search( Map<String, Object> criteria ) ;

	/**
	 * Count all the occurrences
	 * @return
	 */
	public long countAll();
	
}
